version: '3'
services:
  postgres-db:
    image: postgres
    container_name: my-postgres-db
    environment:
      POSTGRES_DB: anonimchat_db
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
